name: mers_app
description: "Mobile Client for MERS (Multimodal Emotion Recognition System)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Networking
  http: ^1.2.0
  
  # Audio Recording & File Management
  record: ^5.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  
  # UI Utilities
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
