name: mers_mobile
description: MERS Mobile Client
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.0
  shared_preferences: ^2.2.0
  record: 5.0.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  camera: ^0.11.3
  image: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  record_platform_interface: 1.0.1

flutter:
  uses-material-design: true
